# Generated by Django 5.1.4 on 2025-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_category_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='repetitions',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
