# Generated by Django 5.1.4 on 2025-01-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_exercise_repetitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
