# Generated by Django 5.1.4 on 2025-01-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_workoutcategory_remove_category_slug_workout_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='portions',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
