# Generated by Django 5.1.4 on 2025-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_meal_portions_alter_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('goal', models.CharField(choices=[('strength', 'Jėgos treniruotės'), ('weight_loss', 'Svorio metimas'), ('muscle_gain', 'Raumenų auginimas')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='portions',
            field=models.IntegerField(),
        ),
    ]
