# Generated by Django 5.1.4 on 2025-01-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_supplement_delete_nutritionplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
        migrations.AddField(
            model_name='supplement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplements/'),
        ),
    ]
