# Generated by Django 5.1.4 on 2025-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nuotrauka',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
