# Generated by Django 5.1.4 on 2025-01-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_supplement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='slug',
        ),
    ]
