# Generated by Django 5.1.4 on 2025-01-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_remove_supplement_rating_remove_supplement_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='image_url',
        ),
    ]
