# Generated by Django 5.1.4 on 2025-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_supplement_image_remove_supplement_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AddField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='total_calories',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='portions',
            field=models.FloatField(),
        ),
    ]
