# Generated by Django 5.1.4 on 2025-01-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='WorkoutCategory',
        ),
    ]
