# Generated by Django 5.1.4 on 2025-01-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_remove_profile_bio_profile_age_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nuotrauka',
        ),
    ]
